apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: gdt-app-worker
description: gdt delivery pipeline for worker
serialPipeline:
 stages:
 - targetId: us-west1
 - targetId: europe-west1 
 - targetId: asia-northeast1
 - targetId: asia-northeast2


---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: us-west1
description: us-west1 cluster
gke:
  cluster: projects/${PROJECT_ID}/locations/us-west1/clusters/gke-auto-us-west1


---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: europe-west1 
description: europe-west1  cluster
gke:
  cluster: projects/${PROJECT_ID}/locations/europe-west1/clusters/gke-auto-europe-west1 

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: asia-northeast1
description: asia-northeast1 cluster
gke:
  cluster: projects/${PROJECT_ID}/locations/asia-northeast1/clusters/gke-auto-asia-northeast1

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: asia-northeast2
description: asia-northeast1 cluster
gke:
  cluster: projects/${PROJECT_ID}/locations/asia-northeast1/clusters/gke-auto-asia-northeast1