apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: global-distributed-testing
build:
  artifacts:
  - image: gcr.io/play-with-anthos-340801/locust-tasks
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - manifests/worker
