apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- worker-deployment.yaml

configMapGenerator:
- name: locust-config
  literals:
    - master_host=MASTER_HOST
    - master_port=5557

namespace: locust

# images:
# - name: locust-tasks
#   newName: us-docker.pkg.dev/PROJECT_ID/gdt-repo/locust-tasks
#   newTag: IMAGE_TAG

