apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: locust-worker
  labels:
    name: locust-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: locust-tasks
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 2000m
              memory: 4096Mi
            requests:
              cpu: 2000m
              memory: 4096Mi
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: master_host
          # startupProbe:
          #   tcpSocket:
          #     port: 5557
          #     host: $(LOCUST_MASTER)
          #   failureThreshold: 30
          #   periodSeconds: 10
      initContainers:
      - name: wait-master-ready
        image: busybox:1.28
        command: ['sh', '-c', "sleep 120"]

      # nodeSelector:
      #   cloud.google.com/gke-spot: "true"
      # terminationGracePeriodSeconds: 25


---
# Optional: PodDisruptionBudget will instruct Kubernetes to ensure at least 1 replica
# is available when possible
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: locust-worker-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: locust-worker

---
# Optional: HorizontalPodAutoscaler will automatically scale the gateway replica count based on
# CPU utilization
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: locust-worker-hpa
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 50
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: locust-worker