apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- master-deployment.yaml
- master-svc.yaml

namespace: locust

# images:
# - name: locust-tasks
#   newName: us-docker.pkg.dev/PROJECT_ID/gdt-repo/locust-tasks
#   newTag: IMAGE_TAG

